// lib/download.ts
// Client-side file generators for card downloads.

export function triggerDownload(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

const safeName = (s: string) =>
  s.replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "study";

// ── Markdown for a single assignment ───────────────────────────────

interface AssignmentLike {
  title:   string;
  summary?: string;
  due?:    string;
  total?:  string;
  tasks?:  Array<{ name: string; time?: string | null; completed?: boolean }>;
  keyRequirements?: string[];
}

export function assignmentToMarkdown(a: AssignmentLike): string {
  const lines: string[] = [];
  lines.push(`# ${a.title}`, "");
  if (a.due)   lines.push(`**Due:** ${a.due}`);
  if (a.total) lines.push(`**Estimated time:** ${a.total}`);
  if (a.due || a.total) lines.push("");
  if (a.summary) { lines.push("## Summary", "", a.summary, ""); }
  if (Array.isArray(a.keyRequirements) && a.keyRequirements.length) {
    lines.push("## Requirements", "");
    a.keyRequirements.forEach((r) => lines.push(`- ${r}`));
    lines.push("");
  }
  if (Array.isArray(a.tasks) && a.tasks.length) {
    lines.push("## Tasks", "");
    a.tasks.forEach((t) => {
      const box = t.completed ? "[x]" : "[ ]";
      const time = t.time ? ` *(${t.time})*` : "";
      lines.push(`- ${box} ${t.name}${time}`);
    });
    lines.push("");
  }
  lines.push("---", "_Generated by StudyAI_");
  return lines.join("\n");
}

export function downloadAssignment(a: AssignmentLike) {
  triggerDownload(
    `${safeName(a.title)}.md`,
    assignmentToMarkdown(a),
    "text/markdown"
  );
}

// ── Markdown for a list of assignments ─────────────────────────────

export function downloadAssignments(assignments: AssignmentLike[]) {
  const body = assignments.map((a) => assignmentToMarkdown(a)).join("\n\n---\n\n");
  triggerDownload("my-assignments.md", body, "text/markdown");
}

// ── ICS for schedule ───────────────────────────────────────────────

interface ScheduleTask {
  title: string;
  when?: string;
  date?: string | null;  // "2026-04-22"
  time?: string | null;  // "18:00"
  hours?: string | null;
}

function pad(n: number) { return String(n).padStart(2, "0"); }

function fmtICSDate(dt: Date): string {
  return (
    dt.getUTCFullYear().toString() +
    pad(dt.getUTCMonth() + 1) +
    pad(dt.getUTCDate()) +
    "T" +
    pad(dt.getUTCHours()) +
    pad(dt.getUTCMinutes()) +
    "00Z"
  );
}

function parseDurationHours(est: string | null | undefined): number {
  if (!est) return 1;
  const h  = est.match(/(\d+(\.\d+)?)\s*(h|hour|hr)/i);
  if (h) return parseFloat(h[1]);
  const m  = est.match(/(\d+)\s*min/i);
  if (m) return parseInt(m[1], 10) / 60;
  return 1;
}

export function scheduleToICS(tasks: ScheduleTask[]): string {
  const now = new Date();
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//StudyAI//EN",
    "CALSCALE:GREGORIAN",
  ];

  tasks.forEach((t, i) => {
    // Build a start Date
    let start: Date;
    if (t.date) {
      const [y, mo, d] = t.date.split("-").map(Number);
      const [hh, mm]   = (t.time ?? "09:00").split(":").map(Number);
      start = new Date(Date.UTC(y, (mo ?? 1) - 1, d ?? 1, hh ?? 9, mm ?? 0));
    } else {
      start = new Date(now.getTime() + (i + 1) * 24 * 3600 * 1000);
    }
    const hrs = parseDurationHours(t.hours ?? null);
    const end = new Date(start.getTime() + hrs * 3600 * 1000);

    lines.push(
      "BEGIN:VEVENT",
      `UID:studyai-${i}-${start.getTime()}@studyai`,
      `DTSTAMP:${fmtICSDate(now)}`,
      `DTSTART:${fmtICSDate(start)}`,
      `DTEND:${fmtICSDate(end)}`,
      `SUMMARY:${(t.title || "Study block").replace(/\n/g, " ")}`,
      "END:VEVENT"
    );
  });

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function downloadSchedule(tasks: ScheduleTask[]) {
  triggerDownload("my-schedule.ics", scheduleToICS(tasks), "text/calendar");
}

// ── Markdown for progress ──────────────────────────────────────────

interface ProgressData {
  streak?:     number;
  hours?:      number;
  goal?:       number;
  tasksDone?:  number;
  tasksTotal?: number;
}

export function progressToMarkdown(p: ProgressData): string {
  const lines: string[] = [];
  lines.push("# My Study Progress", "");
  lines.push(`- **Streak:** ${p.streak ?? 0} days`);
  lines.push(`- **Hours studied:** ${p.hours ?? 0} / ${p.goal ?? 0}`);
  lines.push(`- **Tasks completed:** ${p.tasksDone ?? 0} / ${p.tasksTotal ?? 0}`);
  lines.push("", "---", "_Generated by StudyAI_");
  return lines.join("\n");
}

export function downloadProgress(p: ProgressData) {
  triggerDownload("my-progress.md", progressToMarkdown(p), "text/markdown");
}